CREATE TABLE IF NOT EXISTS `{{prefix}}_media_image_presets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) CHARACTER SET ascii NOT NULL DEFAULT '',
  `title` VARCHAR(190) NOT NULL DEFAULT '',
  `group_label` VARCHAR(120) NOT NULL DEFAULT '',
  `mode` VARCHAR(16) CHARACTER SET ascii NOT NULL DEFAULT 'cover',
  `width` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `height` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `format` VARCHAR(16) CHARACTER SET ascii NOT NULL DEFAULT 'original',
  `quality` TINYINT UNSIGNED NOT NULL DEFAULT 82,
  `webp_twin` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_code` (`code`),
  KEY `idx_sort` (`sort_order`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;
