DELETE FROM `{{prefix}}_constants`
WHERE `name` IN (
  'ADMIN_CAPTCHA', 'ADMIN_EDITMENU', 'ADMIN_MENU', 'ADMIN_MENU_QUICK_ADD',
  'DB_EXPORT_GZ', 'DB_EXPORT_PREFIX', 'DB_EXPORT_TPL', 'DEFAULT_THEME_FOLDER_COLOR',
  'PROFILING_ADMIN', 'SITEMAP_CACHE_LIFETIME', 'SMARTY_COMPILE_CHECK',
  'SMARTY_DEBUGGING', 'SMARTY_USE_SUB_DIRS', 'UPLOAD_GALLERY_DIR',
  'USERS_TIME_SHOW', 'USER_IP', 'CHECK_VERSION', 'GOOGLE_MAP_API_KEY',
  'YANDEX_MAP_API_KEY'
);
